# -*- coding: utf-8 -*-
"""GovAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5aLAKayl4H2PDwnXcTnRaZWhg-2m9Ia
"""

import requests
from pprint import pprint
import matplotlib.pyplot as mychart

def GovAPI(token, mykeyword='วัคซีน', year=2564, limit=20):

  url = 'https://opend.data.go.th/govspending/cgdcontract'
  parameters = {'api-key':token, 
                'keyword':mykeyword, 
                'year':year,        
                'limit':limit}
  r = requests.get(url, params=parameters)
  result = r.json()

  allproject = result['result']
  #print(type(allproject))
  print('Count: ', len(allproject))
  #pprint(allproject[8])

  allbudget = []
  allprojectname = []

  # print('--- parameters ---')
  # print(allproject[0].keys())
  # print('------------------')

  for project in allproject:
    print(project['dept_name'])
    print(project['sum_price_agree'])
    print(project['project_name'])
    print(project['transaction_date'])
    allbudget.append(int(project['sum_price_agree'].replace(',','')))
    allprojectname.append(project['project_name'])
    print('--------------------')

  print('****************************************************')
  print('Keyword: {} Total Budgetary: {:,d} THB'.format(mykeyword, sum(allbudget)))
  print('****************************************************')

  #Bar Chart
  # xbar = range(len(allprojectname))
  # mychart.bar(xbar, allbudget)
  # mychart.xticks(allprojectname)
  # mychart.show()

